### ISSUE TITLE
Total TODO list

### ISSUE THREAD

**Issue by revlis-12** [UNtergas/Project_Reseaux#1]
- [ ] Network Project
    - [ ] Game: `Khang + Phong`
        - [ ] Add time system for game: `Khang` 
        - [ ] Optimize encoding data from game: `Khang + Phong`
        - [ ] Conflict Resolving: `Phong` 
    - [ ] IPC: `Yacine + Tuấn`
    
    - [ ] Network Interface: `Duy + Duke`
        - [ ] Design the model of low level client in network interface: `Duy` 
        - [ ] Process input from inter process communication: `Duke`
        - [ ] Create a P2P (peer-to-peer) network for the connection between players: `Duy + Duke`
        - [ ] Make transferring package in the network: `Duy`
        - [ ] Process output to inter process communication: `Duke`

**Comment by MinPNG** [comment]
Viết issue không ai đọc
